using System.Text;

namespace JustDummies.PlaygroundCatalogueGenerator;

/// <summary>Emits PlaygroundCatalogue.Descriptors.g.cs — plain data driving the Blazor UI.</summary>
public static class DescriptorEmitter {

    public static string Emit(WalkResult result) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Produced by tools/playground-catalogue from the JustDummies assembly referenced in");
        sb.AppendLine("//   Directory.Packages.props. Do not edit by hand — run");
        sb.AppendLine("//   scripts/generate-playground-catalogue.sh and commit the result.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("namespace JustDummies.Playground.Catalogue;");
        sb.AppendLine();
        sb.AppendLine("public static partial class PlaygroundCatalogue {");
        sb.AppendLine();

        sb.AppendLine("    public static readonly IReadOnlyList<MemberDescriptor> EntryPoints = new List<MemberDescriptor> {");
        foreach (var entry in result.EntryPoints.OrderBy(e => e.MethodName, StringComparer.Ordinal)) {
            sb.AppendLine("        " + DescriptorLiteral(entry) + ",");
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, IReadOnlyList<MemberDescriptor>> StepsByReceiverTypeKey = new Dictionary<string, IReadOnlyList<MemberDescriptor>> {");
        foreach (var group in result.Members.Where(m => !m.IsTerminal || true).GroupBy(m => m.ReceiverTypeKey).OrderBy(g => g.Key, StringComparer.Ordinal)) {
            sb.AppendLine($"        [\"{Escape(group.Key)}\"] = new List<MemberDescriptor> {{");
            foreach (var entry in group.OrderBy(e => e.MethodName == "Generate" ? 1 : 0).ThenBy(e => e.MethodName, StringComparer.Ordinal)) {
                sb.AppendLine("            " + DescriptorLiteral(entry) + ",");
            }
            sb.AppendLine("        },");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string DescriptorLiteral(CatalogueEntry entry) {
        var parameters = string.Join(", ", entry.Parameters.Select(p =>
            $"new ParameterDescriptor({Literal(p.Name)}, {Literal(p.TypeKey)}, {Literal(p.Placeholder)})"));

        return "new MemberDescriptor(" +
               $"{Literal(entry.Key)}, {Literal(entry.MethodName)}, {Literal(entry.ReceiverTypeKey)}, {Literal(entry.ReturnTypeKey)}, " +
               $"new List<ParameterDescriptor> {{ {parameters} }}, {Literal(entry.Summary)}, {Literal(HelpUrlFor(entry))})";
    }

    private static string HelpUrlFor(CatalogueEntry entry) =>
        "https://github.com/Reefact/just-dummies#readme";

    private static string Literal(string value) => "\"" + Escape(value) + "\"";

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

}
