using System.Text;

namespace JustDummies.PlaygroundCatalogueGenerator;

/// <summary>
///     Emits PlaygroundCatalogue.Dispatch.g.cs — ordinary, statically typed call sites the trimmer
///     sees and keeps (specification §10.8: no runtime reflection in the playground's own code).
/// </summary>
public static class DispatchEmitter {

    public static string Emit(WalkResult result) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Produced by tools/playground-catalogue from the JustDummies assembly referenced in");
        sb.AppendLine("//   Directory.Packages.props. Do not edit by hand — run");
        sb.AppendLine("//   scripts/generate-playground-catalogue.sh and commit the result.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("namespace JustDummies.Playground.Catalogue;");
        sb.AppendLine();
        sb.AppendLine("public static partial class PlaygroundDispatch {");
        sb.AppendLine();
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, ChainStep> StepsByKey = new Dictionary<string, ChainStep> {");

        foreach (var entry in result.EntryPoints.Concat(result.Members).OrderBy(e => e.Key, StringComparer.Ordinal)) {
            sb.AppendLine($"        [\"{Escape(entry.Key)}\"] = (receiver, rawArguments) => {{");
            sb.Append(StepBody(entry));
            sb.AppendLine("        },");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string StepBody(CatalogueEntry entry) {
        var sb = new StringBuilder();
        var argNames = new List<string>();

        for (var i = 0; i < entry.Parameters.Count; i++) {
            var parameter = entry.Parameters[i];
            var argVar    = $"arg{i}";
            var errVar    = $"argErrorKey{i}";
            var castType  = ClrTypeName(entry.Method.GetParameters()[i].ParameterType);

            sb.AppendLine($"            if (!global::JustDummies.Playground.Catalogue.ArgumentParsing.TryParse(\"{Escape(parameter.TypeKey)}\", rawArguments[{i}], out var {argVar}, out var {errVar}))");
            sb.AppendLine($"                return new ChainResult(receiver, \"{Escape(entry.ReceiverTypeKey)}\", {errVar}, null);");
            argNames.Add($"({castType}){argVar}!");
        }

        var callArgs = string.Join(", ", argNames);

        if (entry.ReceiverClrType is null) {
            // Static entry point on Any (or one of its sibling static classes).
            var declaringType = ClrTypeName(entry.Method.DeclaringType!);
            var call = $"global::{declaringType}.{entry.MethodName}({callArgs})";

            sb.AppendLine("            try {");
            sb.AppendLine($"                var produced = {call};");
            sb.AppendLine($"                return new ChainResult(produced, \"{Escape(entry.ReturnTypeKey)}\", null, null);");
            sb.AppendLine("            } catch (Exception refused) when (refused is DummyException or ArgumentException) {");
            sb.AppendLine("                return new ChainResult(receiver, PlaygroundCatalogue.EntryPointReceiver, null, refused.Message);");
            sb.AppendLine("            }");
            return sb.ToString();
        }

        var receiverType = ClrTypeName(entry.ReceiverClrType);
        sb.AppendLine($"            var typed = (global::{receiverType})receiver!;");
        sb.AppendLine("            try {");
        sb.AppendLine($"                var produced = typed.{entry.MethodName}({callArgs});");
        sb.AppendLine($"                return new ChainResult(produced, \"{Escape(entry.ReturnTypeKey)}\", null, null);");
        sb.AppendLine("            } catch (Exception refused) when (refused is DummyException or ArgumentException) {");
        sb.AppendLine($"                return new ChainResult(receiver, \"{Escape(entry.ReceiverTypeKey)}\", null, refused.Message);");
        sb.AppendLine("            }");

        return sb.ToString();
    }

    private static string ClrTypeName(Type type) => type.FullName ?? type.Name;

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

}
