using System.Text;

namespace JustDummies.PlaygroundCatalogueGenerator;

/// <summary>
///     Emits PlaygroundCatalogue.Excluded.g.md — the audited list of every public member left out
///     of the catalogue, with its reason (specification §10.6: "a member can be excluded, with a
///     mandatory reason"). Most reasons are auto-detected structurally; the rest come from
///     excluded-members.jsonc.
/// </summary>
public static class ExclusionReport {

    public static string Emit(WalkResult result) {
        var sb = new StringBuilder();
        sb.AppendLine("<!-- auto-generated by tools/playground-catalogue — do not edit by hand -->");
        sb.AppendLine("# Playground catalogue — excluded members");
        sb.AppendLine();
        sb.AppendLine("Every public JustDummies member the generator found but did not catalogue, and why.");
        sb.AppendLine("Specification §10.5/§10.6: an omission must be either catalogued or excluded with a");
        sb.AppendLine("stated reason — this file is that reason, kept current on every generation.");
        sb.AppendLine();

        sb.AppendLine($"## Auto-detected ({result.AutoExcluded.Count})");
        sb.AppendLine();
        foreach (var excluded in result.AutoExcluded.OrderBy(e => e.Member, StringComparer.Ordinal)) {
            sb.AppendLine($"- `{excluded.Member}` — {excluded.Reason}");
        }
        sb.AppendLine();

        sb.AppendLine($"## Manual (`excluded-members.jsonc`) ({result.ManuallyExcluded.Count})");
        sb.AppendLine();
        foreach (var excluded in result.ManuallyExcluded.OrderBy(e => e.Member, StringComparer.Ordinal)) {
            sb.AppendLine($"- `{excluded.Member}` — {excluded.Reason}");
        }
        sb.AppendLine();

        // Excluded from the catalogue is no longer the same thing as invisible. The combo names
        // the ones the interface cannot express, disabled, so that a visitor is not left to infer
        // the library stops where this form does — an audit of what was left out should be able to
        // tell the two apart without reading the generator.
        sb.AppendLine($"## Named in the playground as unavailable ({result.Unavailable.Count})");
        sb.AppendLine();
        sb.AppendLine("Auto-detected exclusions the interface cannot express, shown in the method combo as");
        sb.AppendLine("disabled entries rather than hidden. One per name per receiver: the combo prints these");
        sb.AppendLine("without arguments, so overloads would be repeats of one dead line.");
        sb.AppendLine();
        foreach (var entry in result.Unavailable) {
            sb.AppendLine($"- `{entry.ReceiverTypeKey}.{entry.MethodName}`");
        }
        sb.AppendLine();

        if (result.UnusedManualExclusions.Count > 0) {
            sb.AppendLine($"## Stale entries in `excluded-members.jsonc` ({result.UnusedManualExclusions.Count})");
            sb.AppendLine();
            sb.AppendLine("Matched no discovered member on this run — the library likely renamed or removed");
            sb.AppendLine("what these used to name. Worth pruning.");
            sb.AppendLine();
            foreach (var key in result.UnusedManualExclusions) {
                sb.AppendLine($"- `{key}`");
            }
        }

        return sb.ToString();
    }

}
