import { expect, test } from '@playwright/test';

import { watch, type PageComplaints } from './support/watch';

/**
 * The playground works.
 *
 * This is the check with the least competition. `verify-output.sh` asserts that the
 * playground's `<base href>` matches where the playground was copied, which is a claim about
 * two strings agreeing; the failure it guards against is every asset answering 404 and the
 * page rendering nothing at all, with no error printed anywhere. Those are not the same
 * claim, and the deployment guide lists the blank playground in its troubleshooting table
 * because the difference has been met.
 *
 * So this one loads it and uses it. The library is compiled to WebAssembly and executes in
 * the browser with no backend behind it; if the chain is whole, a value comes back that
 * satisfies the constraints the page declares.
 */
test.describe('the playground', () => {

    test('draws a value that satisfies the expression on the page', async ({ page }) => {
        const complaints: PageComplaints = await watch(page);

        await page.goto('/playground/');

        const value = page.locator('#generated-value');

        // The expression shown on the page is `Any.String().NonEmpty().StartingWith("ORD-")
        // .WithMaxLength(20)`, so the drawn value is what proves the library ran rather than
        // that the markup rendered: a page served without its WebAssembly leaves this empty.
        await expect(value).toHaveText(/^ORD-.*$/);

        const drawn: string = (await value.textContent()) ?? '';

        expect(drawn.length, `drawn "${drawn}" is longer than the declared maximum`).toBeLessThanOrEqual(20);

        // Nothing may have 404'd on the way. This is the blank-page defect stated as an
        // assertion: the base href and the copy destination disagree, every asset misses, and
        // the page renders — empty, and quietly.
        expect(complaints.failed, 'the playground asked for something that was not there').toEqual([]);
        expect(complaints.errors, 'the playground threw while starting').toEqual([]);
    });

    test('draws again when asked', async ({ page }) => {
        await page.goto('/playground/');

        const value = page.locator('#generated-value');

        await expect(value).toHaveText(/^ORD-.*$/);

        /*
         * Ten draws, and at least two of them different — rather than "the next one differs
         * from this one", which is what this check said first and which flaked on the day it
         * was written.
         *
         * Measured over 300 consecutive draws: the length is uniform across the declared
         * range, so 7% of them come back as the bare prefix "ORD-" with nothing after it,
         * and two consecutive draws matched 2 times in 299 — a red roughly every 150 runs.
         * Ten draws collapsing to one value is about one run in a hundred million, and a
         * button that has stopped drawing produces it every time.
         */
        const drawn: string[] = [];
        const button = page.getByRole('button', { name: 'Generate again' });

        for (let press: number = 0; press < 10; press += 1) {
            await button.click();
            await expect(value).toHaveText(/^ORD-.*$/);

            drawn.push((await value.textContent()) ?? '');
        }

        expect(new Set(drawn).size, `ten presses drew one value: ${drawn[0]}`).toBeGreaterThan(1);

        for (const text of drawn) {
            expect(text.length, `drawn "${text}" is longer than the declared maximum`).toBeLessThanOrEqual(20);
        }
    });

    test('says which version of the library it is running', async ({ page }) => {
        await page.goto('/playground/');

        // Read off the loaded assembly rather than written beside it, so the claim cannot go
        // stale — the check is that the reading worked, not that a particular version shipped.
        await expect(page.locator('.version')).toHaveText(/Generated by JustDummies \S+, running in this browser\./);
        await expect(page.locator('.version')).not.toHaveText(/unknown/);
    });

    test('shows no framework error banner', async ({ page }) => {
        await page.goto('/playground/');

        await expect(page.locator('#generated-value')).toHaveText(/^ORD-.*$/);

        // Blazor's own unhandled-error element. It ships in the markup and stays hidden; a
        // visible one means the runtime gave up, and it says so in a corner of the screen
        // rather than by failing to render.
        await expect(page.locator('#blazor-error-ui')).toBeHidden();
    });

    /**
     * The playground counts as part of the site, so it carries the same footer — rebuilt
     * in Blazor (Layout/MainLayout.razor) rather than shared, since Astro and Blazor have
     * no rendering system in common. What both halves must still agree on is that a link
     * back to the site survives `<base href="/playground/" />`: a bare "about" would
     * resolve to /playground/about, a page that does not exist, so the links are asserted
     * root-relative rather than merely present.
     */
    test('carries the site\'s footer, with links that survive its own <base href>', async ({ page }) => {
        await page.goto('/playground/');

        const footer = page.locator('.site-footer');

        await expect(footer).toBeVisible();
        await expect(footer.locator('a[href="/about/"]')).toBeVisible();
        await expect(footer.locator('a[href="/release-notes/"]')).toBeVisible();
        await expect(footer.locator('a[href="/privacy/"]')).toBeVisible();

        const repository = footer.locator('a[href="https://github.com/Reefact/justdummies.io"]');

        await expect(repository).toBeVisible();
        await expect(repository).toHaveAttribute('target', '_blank');
        await expect(repository).toHaveAttribute('rel', /noopener/);
    });

    test('carries the same footer on its own not-found page', async ({ page }) => {
        await page.goto('/playground/not-found');

        await expect(page.locator('.site-footer')).toBeVisible();
    });

    test('carries no footer inside the hero widget embedded in the landing page', async ({ page }) => {
        await page.goto('/playground/hero');

        // BareLayout, deliberately: the widget already sits inside a page that carries the
        // real footer around it, so a second one here would be a duplicate, not a match.
        await expect(page.locator('.site-footer')).toHaveCount(0);
    });

});
