namespace JustDummies.Playground.Localization;

/// <summary>
///     Every string the playground displays, in every locale it supports.
///
///     Mirrors the intent of the site's own <c>i18n/ui.ts</c> — English is the source, a
///     locale is a complete translation of it, nothing falls back silently — without sharing
///     its code, because the two are different languages and different runtimes.
///
///     What does NOT belong here: anything a <c>DummyException</c> (or a subclass) says. Those
///     messages come from the published library, not from this project, and rewording them
///     would be the playground's opinion of the library's diagnostics rather than the
///     diagnostics themselves.
/// </summary>
public static class PlaygroundStrings {

    /// <summary>The locale named by a <c>?lang=</c> value, or <see cref="Locale.En" /> for anything else.</summary>
    public static Locale Parse(string? tag) {
        return tag?.Trim().ToLowerInvariant() switch {
            "fr" => Locale.Fr,
            _    => Locale.En,
        };
    }

    /// <summary>The <c>?lang=</c> value a locale round-trips through, for building a URL.</summary>
    public static string Tag(Locale locale) {
        return locale switch {
            Locale.Fr => "fr",
            _         => "en",
        };
    }

    /// <summary>
    ///     The name of a locale, written in that locale — "English", "Français" — never
    ///     translated into whichever one the reader is currently in. Mirrors
    ///     <c>localeNames</c> in the site's <c>i18n/ui.ts</c>: a language selector names its
    ///     options in the reader's possible destinations, not in the language they are leaving.
    /// </summary>
    public static string Name(Locale locale) {
        return locale switch {
            Locale.Fr => "Français",
            _         => "English",
        };
    }

    private static readonly Dictionary<string, string> En = new() {
        ["brand.tagline"] = "Just dummies — but seriously powerful ones.",

        ["nav.github"]     = "GitHub",
        ["language.label"] = "Language",

        ["hero.aria.prefix"]   = "prefix",
        ["hero.aria.contains"] = "contained text",
        ["hero.aria.length"]   = "length",
        ["hero.generate"]      = "Generate",
        ["hero.running"]       = "running here, JustDummies {0}",

        ["playground.title"] = "Playground",
        ["playground.lede"] =
            "The visitor edits only what sits between <code>Any.</code> and <code>.Generate()</code>. " +
            "The parser that will read that fragment is not built yet, so this shell runs one fixed " +
            "expression instead — enough to prove the chain the real playground depends on: the " +
            "published library, executing in the browser, with no backend behind it.",
        ["playground.generateAgain"] = "Generate again",
        ["playground.generatedBy"]   = "Generated by JustDummies {0}, running in this browser.",

        ["limit.length"] = "This playground caps the length at {0} characters; the library itself has no such limit.",
        ["limit.text"]   = "This playground caps this field at {0} characters; the library itself has no such limit.",

        ["notFound.title"] = "Not found",
        ["notFound.lede"] =
            "There is no such page in the playground. <a href=\"{0}\">Start over</a>, " +
            "or <a href=\"{1}\">go back to the site</a>.",

        ["footer.nav"]        = "Footer",
        ["footer.about"]      = "About",
        ["footer.privacy"]    = "Privacy",
        ["footer.repository"] = "Source code",
        ["state.newTab"]      = "opens in a new tab",
    };

    private static readonly Dictionary<string, string> Fr = new() {
        ["brand.tagline"] = "Juste des dummies, mais redoutablement efficaces.",

        ["nav.github"]     = "GitHub",
        ["language.label"] = "Langue",

        ["hero.aria.prefix"]   = "préfixe",
        ["hero.aria.contains"] = "texte contenu",
        ["hero.aria.length"]   = "longueur",
        ["hero.generate"]      = "Générer",
        ["hero.running"]       = "s'exécute ici, JustDummies {0}",

        ["playground.title"] = "Playground",
        ["playground.lede"] =
            "Le visiteur ne modifie que ce qui se trouve entre <code>Any.</code> et <code>.Generate()</code>. " +
            "L'analyseur qui lira ce fragment n'est pas encore construit, donc cette ébauche exécute une " +
            "expression fixe à la place — suffisant pour prouver la chaîne dont dépend le vrai playground : " +
            "la librairie publiée, exécutée dans le navigateur, sans aucun backend derrière elle.",
        ["playground.generateAgain"] = "Générer à nouveau",
        ["playground.generatedBy"]   = "Générée par JustDummies {0}, exécutée dans ce navigateur.",

        ["limit.length"] = "Ce playground limite la longueur à {0} caractères ; la librairie elle-même n'impose aucune limite.",
        ["limit.text"]   = "Ce playground limite ce champ à {0} caractères ; la librairie elle-même n'impose aucune limite.",

        ["notFound.title"] = "Introuvable",
        ["notFound.lede"] =
            "Cette page n'existe pas dans le playground. <a href=\"{0}\">Recommencer</a>, " +
            "ou <a href=\"{1}\">revenir sur le site</a>.",

        ["footer.nav"]        = "Pied de page",
        ["footer.about"]      = "À propos",
        ["footer.privacy"]    = "Confidentialité",
        ["footer.repository"] = "Code source",
        ["state.newTab"]      = "ouvre un nouvel onglet",
    };

    private static readonly IReadOnlyDictionary<Locale, IReadOnlyDictionary<string, string>> All =
        new Dictionary<Locale, IReadOnlyDictionary<string, string>> {
            [Locale.En] = En,
            [Locale.Fr] = Fr,
        };

    /// <summary>
    ///     The string named by <paramref name="key" />, in <paramref name="locale" />, with
    ///     <paramref name="args" /> substituted into it.
    ///
    ///     A missing key throws <see cref="KeyNotFoundException" /> rather than falling back to
    ///     English: a silent fallback is exactly the half-translated page the site's own i18n
    ///     rules (§6.4) refuse to ship.
    /// </summary>
    public static string T(Locale locale, string key, params object[] args) {
        string template = All[locale][key];

        return args.Length == 0 ? template : string.Format(template, args);
    }

}
