namespace JustDummies.Playground.Localization;

/// <summary>
///     Every string the playground displays, in every locale it supports.
///
///     Mirrors the intent of the site's own <c>i18n/ui.ts</c> — English is the source, a
///     locale is a complete translation of it, nothing falls back silently — without sharing
///     its code, because the two are different languages and different runtimes.
///
///     What does NOT belong here: anything a <c>DummyException</c> (or a subclass) says. Those
///     messages come from the published library, not from this project, and rewording them
///     would be the playground's opinion of the library's diagnostics rather than the
///     diagnostics themselves.
/// </summary>
public static class PlaygroundStrings {

    /// <summary>The locale named by a <c>?lang=</c> value, or <see cref="Locale.En" /> for anything else.</summary>
    public static Locale Parse(string? tag) {
        return tag?.Trim().ToLowerInvariant() switch {
            "fr" => Locale.Fr,
            _    => Locale.En,
        };
    }

    /// <summary>The <c>?lang=</c> value a locale round-trips through, for building a URL.</summary>
    public static string Tag(Locale locale) {
        return locale switch {
            Locale.Fr => "fr",
            _         => "en",
        };
    }

    /// <summary>
    ///     The name of a locale, written in that locale — "English", "Français" — never
    ///     translated into whichever one the reader is currently in. Mirrors
    ///     <c>localeNames</c> in the site's <c>i18n/ui.ts</c>: a language selector names its
    ///     options in the reader's possible destinations, not in the language they are leaving.
    /// </summary>
    public static string Name(Locale locale) {
        return locale switch {
            Locale.Fr => "Français",
            _         => "English",
        };
    }

    /// <summary>
    ///     A French string, paired with the exact English text it was translated from —
    ///     <see cref="TranslatedFrom" /> is a snapshot, not a live reference to <see cref="En" />.
    ///     The static constructor below compares that snapshot against the current English
    ///     value for the same key: if someone edits <see cref="En" /> without revisiting the
    ///     translation, the two stop matching, and this is what notices.
    /// </summary>
    private readonly record struct Translation(string Text, string TranslatedFrom);

    private static readonly Dictionary<string, string> En = new() {
        ["brand.tagline"] = "Just dummies — but seriously powerful ones.",

        ["nav.github"]     = "GitHub",
        ["language.label"] = "Language",

        ["hero.aria.prefix"]    = "prefix",
        ["hero.aria.contains"]  = "contained text",
        ["hero.aria.length"]    = "length",
        ["hero.generate"]       = "Generate",
        ["hero.running"]        = "running here, JustDummies {0}",
        ["hero.lengthRequired"] = "Enter a length to generate.",
        // Same word as the site's own "sample.produced" (ui.ts) — the label on the result
        // this widget replaces, so the two read as the same caption.
        ["hero.produced"]       = "produced",

        ["playground.title"] = "Playground",
        ["playground.lede"] =
            "The visitor edits only what sits between <code>Any.</code> and <code>.Generate()</code>. " +
            "The parser that will read that fragment is not built yet, so this shell runs one fixed " +
            "expression instead — enough to prove the chain the real playground depends on: the " +
            "published library, executing in the browser, with no backend behind it.",
        ["playground.generateAgain"] = "Generate again",
        ["playground.generatedBy"]   = "Generated by JustDummies {0}, running in this browser.",

        ["limit.length"] = "This playground caps the length at {0} characters; the library itself has no such limit.",
        ["limit.text"]   = "This playground caps this field at {0} characters; the library itself has no such limit.",

        ["notFound.title"] = "Not found",
        ["notFound.lede"] =
            "There is no such page in the playground. <a href=\"{0}\">Start over</a>, " +
            "or <a href=\"{1}\">go back to the site</a>.",

        ["footer.nav"]          = "Footer",
        ["footer.about"]        = "About",
        ["footer.releaseNotes"] = "Release notes",
        ["footer.privacy"]      = "Privacy",
        ["footer.repository"]   = "Source code",
        ["state.newTab"]      = "opens in a new tab",

        // The one piece of the pre-boot shell (wwwroot/index.html) that still has to be
        // relocalized after boot: #blazor-error-ui sits outside Blazor's render tree and is
        // translated once, synchronously, before the runtime even starts. These two keys are
        // what LocaleState.Set(...) hands back to that same banner when the reader switches
        // language afterwards — see the KNOWN DUPLICATION note in index.html for why the
        // pre-boot script still carries its own literal copy rather than awaiting this class.
        ["errorBanner.message"] = "Something went wrong.",
        ["errorBanner.reload"]  = "Reload",
    };

    private static readonly Dictionary<string, Translation> Fr = new() {
        ["brand.tagline"] = new("Juste des dummies, mais redoutablement efficaces.", "Just dummies — but seriously powerful ones."),

        ["nav.github"]     = new("GitHub", "GitHub"),
        ["language.label"] = new("Langue", "Language"),

        ["hero.aria.prefix"]    = new("préfixe", "prefix"),
        ["hero.aria.contains"]  = new("texte contenu", "contained text"),
        ["hero.aria.length"]    = new("longueur", "length"),
        ["hero.generate"]       = new("Générer", "Generate"),
        ["hero.running"]        = new("s'exécute ici, JustDummies {0}", "running here, JustDummies {0}"),
        ["hero.lengthRequired"] = new("Indiquez une longueur pour générer.", "Enter a length to generate."),
        ["hero.produced"]       = new("produit", "produced"),

        ["playground.title"] = new("Playground", "Playground"),
        ["playground.lede"] = new(
            "Le visiteur ne modifie que ce qui se trouve entre <code>Any.</code> et <code>.Generate()</code>. " +
            "L'analyseur qui lira ce fragment n'est pas encore construit, donc cette ébauche exécute une " +
            "expression fixe à la place — suffisant pour prouver la chaîne dont dépend le vrai playground : " +
            "la librairie publiée, exécutée dans le navigateur, sans aucun backend derrière elle.",
            "The visitor edits only what sits between <code>Any.</code> and <code>.Generate()</code>. " +
            "The parser that will read that fragment is not built yet, so this shell runs one fixed " +
            "expression instead — enough to prove the chain the real playground depends on: the " +
            "published library, executing in the browser, with no backend behind it."),
        ["playground.generateAgain"] = new("Générer à nouveau", "Generate again"),
        ["playground.generatedBy"]   = new("Générée par JustDummies {0}, exécutée dans ce navigateur.", "Generated by JustDummies {0}, running in this browser."),

        ["limit.length"] = new(
            "Ce playground limite la longueur à {0} caractères ; la librairie elle-même n'impose aucune limite.",
            "This playground caps the length at {0} characters; the library itself has no such limit."),
        ["limit.text"] = new(
            "Ce playground limite ce champ à {0} caractères ; la librairie elle-même n'impose aucune limite.",
            "This playground caps this field at {0} characters; the library itself has no such limit."),

        ["notFound.title"] = new("Introuvable", "Not found"),
        ["notFound.lede"] = new(
            "Cette page n'existe pas dans le playground. <a href=\"{0}\">Recommencer</a>, " +
            "ou <a href=\"{1}\">revenir sur le site</a>.",
            "There is no such page in the playground. <a href=\"{0}\">Start over</a>, " +
            "or <a href=\"{1}\">go back to the site</a>."),

        ["footer.nav"]          = new("Pied de page", "Footer"),
        ["footer.about"]        = new("À propos", "About"),
        ["footer.releaseNotes"] = new("Notes de version", "Release notes"),
        ["footer.privacy"]      = new("Confidentialité", "Privacy"),
        ["footer.repository"]   = new("Code source", "Source code"),
        ["state.newTab"]      = new("ouvre un nouvel onglet", "opens in a new tab"),

        ["errorBanner.message"] = new("Une erreur est survenue.", "Something went wrong."),
        ["errorBanner.reload"]  = new("Recharger", "Reload"),
    };

    /// <summary>
    ///     TypeScript gives the site's own dictionary the key-parity half of this guarantee for
    ///     free — <c>fr</c> declared as <c>Record&lt;UiKey, string&gt;</c> makes a missing or
    ///     extra key a compile error (<c>i18n/ui.ts</c>). C# has no equivalent structural check,
    ///     so this is the closest a plain static class gets: an explicit static constructor runs
    ///     before <em>any</em> member of this type is first touched, so a key added to one locale
    ///     and not the other, or an English string revised without its translation, surfaces the
    ///     moment the playground starts — in every environment, not only the one where a French
    ///     reader happens to hit it first. <c>tools/playground-i18n-guard</c> forces this
    ///     constructor to run during the build itself, so a stale translation fails CI rather
    ///     than only ever failing at someone's runtime (§6.4).
    /// </summary>
    static PlaygroundStrings() {
        string[] onlyInEn = En.Keys.Except(Fr.Keys).OrderBy(key => key, StringComparer.Ordinal).ToArray();
        string[] onlyInFr = Fr.Keys.Except(En.Keys).OrderBy(key => key, StringComparer.Ordinal).ToArray();

        if (onlyInEn.Length > 0 || onlyInFr.Length > 0) {
            throw new InvalidOperationException(
                "PlaygroundStrings: En and Fr must declare exactly the same keys (§6.4)."
                + (onlyInEn.Length > 0 ? $" Missing from Fr: {string.Join(", ", onlyInEn)}." : string.Empty)
                + (onlyInFr.Length > 0 ? $" Missing from En: {string.Join(", ", onlyInFr)}." : string.Empty));
        }

        // §6.4: "a modification of the English content marks its translation stale, and CI
        // reports it." A key present on both sides can still ship a French string answering a
        // question the English no longer asks — this is what catches that, by comparing what
        // French says it was translated from against what English actually says today.
        string[] stale = Fr
            .Where(entry => En[entry.Key] != entry.Value.TranslatedFrom)
            .Select(entry => entry.Key)
            .OrderBy(key => key, StringComparer.Ordinal)
            .ToArray();

        if (stale.Length > 0) {
            throw new InvalidOperationException(
                "PlaygroundStrings: the French translation is stale for keys whose English text changed "
                + $"since it was translated (§6.4): {string.Join(", ", stale)}.");
        }
    }

    /// <summary>
    ///     The string named by <paramref name="key" />, in <paramref name="locale" />, with
    ///     <paramref name="args" /> substituted into it.
    ///
    ///     A missing key throws <see cref="KeyNotFoundException" /> rather than falling back to
    ///     English: a silent fallback is exactly the half-translated page the site's own i18n
    ///     rules (§6.4) refuse to ship.
    /// </summary>
    public static string T(Locale locale, string key, params object[] args) {
        string template = locale == Locale.Fr ? Fr[key].Text : En[key];

        return args.Length == 0 ? template : string.Format(template, args);
    }

}
