/**
 * The public surface of the `JustDummies` and `JustDummies.Xunit` packages, as reflection
 * found it — the /api pages' only source, so a signature or a doc comment shown there is one
 * the published packages actually carry.
 *
 * Generated by reflecting on the real NuGet packages (`tools/api-catalogue`,
 * `scripts/generate-api-catalogue.sh`), never typed here: every signature, every summary,
 * every parameter comes off the assemblies and their XML documentation. The one thing a
 * person still decides is which category a type belongs to, and that decision lives in the
 * generator, not in this file or in a page — an unplaced type fails the build there rather
 * than silently missing a page here.
 *
 * The doc comments stay in English in both locales, deliberately, the same way `about.ts`'s
 * exception messages do: they come from a package published outside this repository and
 * reflect that package's own English identifiers, not prose written for this site.
 */
import catalogueDocument from './generated/api-catalogue.json';

export interface ApiMember {
    /** The declaration a reader would type: `AnyString WithLength(int length)`. */
    readonly signature: string;
    /** The library's own doc comment, English always — null when the member carries none. */
    readonly summary: string | null;
}

export interface ApiEntry {
    /** Stable across regenerations as long as the type's own name doesn't change — an anchor and a search key. */
    readonly id: string;
    /** The name a reader recognises: `AnyArray<T>`, not the reflected `AnyArray\`1`. */
    readonly name: string;
    /** `class`, `sealed class`, `abstract class`, `static class`, `interface`, `enum`, or `static method` for an entry with no declaring type of its own. */
    readonly kind: string;
    /** The bare declaration, with no base type or interface list — those are `extends` and `implements` below. */
    readonly signature: string;
    readonly summary: string | null;
    /** A base type worth stating, or null — `object` and the other roots nobody declares against on purpose are already filtered out. */
    readonly extends: string | null;
    readonly implements: readonly string[];
    /**
     * The static `Any` (or `AnyContext`) method that produces this entry — `Any.String()` for
     * `AnyString` — attached here rather than repeated as its own catalogue entry. Null for a
     * type nothing constructs this way: an abstract base, an exception, an entry that is
     * itself a loose static method.
     */
    readonly entryPoints: readonly ApiMember[] | null;
    readonly properties: readonly ApiMember[];
    readonly constructors: readonly ApiMember[];
    /**
     * Declared members only — an inherited method is documented once, on the type that
     * declares it, never repeated on every type that shares it. `AnyArray<T>` lists `Distinct`
     * alone; the count and containment surface it shares with every other collection generator
     * is `AnyCollection`'s entry.
     */
    readonly methods: readonly ApiMember[];
}

export interface ApiCategory {
    readonly slug: string;
    readonly entries: readonly ApiEntry[];
}

interface ApiCatalogueDocument {
    readonly library: {
        readonly libraryVersion: string;
        readonly xunitVersion: string;
    };
    readonly categories: readonly ApiCategory[];
}

const document: ApiCatalogueDocument = catalogueDocument as ApiCatalogueDocument;

/** The version of `JustDummies` this catalogue was reflected from — what a reader who installs today actually gets. */
export const apiLibraryVersion: string = document.library.libraryVersion;

/** The version of `JustDummies.Xunit` the `[Reproducible]` entry was reflected from. */
export const apiXunitVersion: string = document.library.xunitVersion;

/**
 * Every entry in one category, in the order the generator wrote them (alphabetical by name).
 * An unknown slug throws rather than rendering an empty page: a category a page asks for by
 * name has to exist, or the request is a typo, not a page with nothing to say.
 */
export function apiCategory(slug: string): ApiCategory {
    const found: ApiCategory | undefined = document.categories.find((category) => category.slug === slug);

    if (found === undefined) {
        throw new Error(
            `No API category "${slug}". Either the slug is wrong, or tools/api-catalogue/Program.cs no longer emits it — ` +
                're-run scripts/generate-api-catalogue.sh and check apps/site/src/generated/api-catalogue.json.',
        );
    }

    return found;
}

/** Every category, in the order the generator wrote them — the shape of the /api index page. */
export function allApiCategories(): readonly ApiCategory[] {
    return document.categories;
}
