<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Ordering.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JustDummies" />
    <PackageReference Include="JustDummies.Xunit" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../snippet-validation/JustDummies.SnippetValidation.csproj" />
  </ItemGroup>

</Project>
