// Generate dist/_headers, the response headers Cloudflare serves the artefact with.
//
// It is generated rather than versioned for one reason: the Content Security Policy
// has to name a hash that only the build knows.
//
// Blazor writes an inline <script type="importmap"> into the playground's shell,
// carrying the fingerprinted asset names and their integrity hashes. It is inline,
// so a policy of `script-src 'self'` blocks it, and a blocked importmap means the
// runtime resolves nothing and the playground never starts — with a blank page and a
// console message as the only symptom. The escapes are 'unsafe-inline', which would
// disable inline-script protection across the whole site to accommodate one tag, or
// a hash of that exact tag. This takes the hash, and recomputes it every build
// because the fingerprints inside it change every build.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');

/**
 * The bytes a browser hashes are exactly those between the script tag and its
 * closing tag — no trimming, no re-indenting.
 */
function inlineScriptHashes(html) {
    const pattern = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g;
    const hashes = [];

    for (const match of html.matchAll(pattern)) {
        const body = match[1];
        if (body.length === 0) {
            continue;
        }
        hashes.push(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
    }

    return hashes;
}

const playgroundShell = readFileSync(join(dist, 'playground', 'index.html'), 'utf8');
const scriptHashes = inlineScriptHashes(playgroundShell);

if (scriptHashes.length === 0) {
    console.error('generate-headers: no inline script found in the playground shell.');
    console.error('  Blazor has always emitted an importmap there. Either the template changed');
    console.error('  and the policy can tighten, or the shell was not built. Check before assuming.');
    process.exit(1);
}

const contentSecurityPolicy = [
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    // Nothing embeds this site, which is what CSP offers instead of X-Frame-Options.
    "frame-ancestors 'none'",
    // The site posts no form anywhere. The day it does, this is the line to revisit.
    "form-action 'none'",
    "img-src 'self' data:",
    "font-src 'self'",
    // Kept at 'self' by emitting every stylesheet as a file: see inlineStylesheets in
    // astro.config.mjs, and the assertion in verify-output.sh.
    "style-src 'self'",
    // The playground makes no network call at all, so this only has to cover the
    // framework fetching its own assets.
    "connect-src 'self'",
    // 'wasm-unsafe-eval' is what compiling a WebAssembly module requires, and it is
    // NOT 'unsafe-eval': it permits WebAssembly compilation and nothing else — no
    // eval, no Function constructor, no inline script execution.
    `script-src 'self' 'wasm-unsafe-eval' ${scriptHashes.join(' ')}`,
    "worker-src 'self' blob:",
].join('; ');

const headers = `# GENERATED by scripts/generate-headers.mjs — do not edit by hand.
#
# The Content Security Policy below names a hash of the playground's inline
# importmap, which changes whenever an asset fingerprint changes. Editing this file
# by hand therefore breaks the playground at the next build.

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
  Content-Security-Policy: ${contentSecurityPolicy}

# HTML is always revalidated: it is the document that names every fingerprinted
# asset, so a stale copy pins stale assets no matter how they are cached.
/*.html
  Cache-Control: public, max-age=0, must-revalidate

/
  Cache-Control: public, max-age=0, must-revalidate

# Astro fingerprints everything under /_astro/, so a changed file is a changed URL
# and the old one can be kept forever.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

# The framework is fingerprinted too, but the publish also emits unfingerprinted
# aliases beside the fingerprinted files (dotnet.js next to dotnet.<hash>.js). A
# week is long enough to matter and short enough that an alias cannot pin a stale
# runtime. Revisit with measurements rather than by feel.
/playground/_framework/*
  Cache-Control: public, max-age=604800
`;

writeFileSync(join(dist, '_headers'), headers, 'utf8');

console.log(`  dist/_headers  (${scriptHashes.length} inline script hash(es) pinned)`);
